name: Dmonewpiper
on:
   workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Run a one-line script
       run: echo Deploy Dev

deploy-dev:
  runs-on: ubuntu-latest
  enviroment:
    name: dev
    url: 'julioarruda.com'
    needs: build
    steps:
     - name: Run a one-line script
       run: echo Deploy Dev
        
        
deploy-hmg:
 runs-on: ubuntu-latest
 enviroment:
   name: hmg
   url: 'testepipe.com'
needs: deploy-dev
steps:
  - name: Run a one-line script
    run: echo Deploy HMG
 
 deploy-prd:
    runs-on: ubuntu-latest
    enviroment:
      name: prd
      url: 'testepipe.com' 
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
     
        
     
